### PR TITLE
Add back to top component

### PR DESCRIPTION
**Pull request by albinazs**
### Checklist

- [x] Include a description of your pull request and instructions for the reviewer to verify your work.
- [ ] Link to the issue if this PR is issue-specific.
- [x] Create/update the corresponding story if this includes a UI component.
- [x] Create/update documentation. If not included, tell us why.
- [x] List the environments / browsers in which you tested your changes.
- [x] Tests, linting, or other required checks are passing.
- [x] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../releases); good ones make that easier to scan.
  - PRs will be broadly categorized in the change log, but for even easier scanning, consider prefixing with a component name or other useful categorization, e.g., "BaseButton: fix layout bug", or "Storybook: Update dependencies".
- [x] PR has been tagged with a [SemVer](https://semver.org/) label and a [general category label](https://github.com/nasa-jpl/explorer-1/blob/52994b671411f55961d7beb8851d4580ac3f434f/.github/release-drafter.config.yml#L21-L39), or skip-changelog.
  - These tags are used to do the aforementioned broad categorization in the change log and determine what the next release's version number should be.
  - [Release Drafter](https://github.com/marketplace/actions/release-drafter) will attempt to do the category labeling for you! Please double-check its work.

## Description

In this PR I've implemented `BackToTop` component, part of the www-frontend Timeline page:
- modified `BaseButton` component to make it more flexible: added the `IconBefore` property to control the icon's position and `label-text` span to select and style the inner text
- reused a modified `IconDropdown` as there's no exact match for this component, and other options (like, `IconPrev`) required a bit hacky styling
- added prop `threshold` to control the scroll position at which BackToTop becomes visible. Defaults to 300
- added prop `scrollTo` to control the vertical scroll position to which the page will scroll when BackToTop is clicked. Defaults to 0
- added a possibility to add multiple back-to-tops
- improved scrolling performance with passive event listener and debouncing
- positioning of the component is not hard-coded and will be handled when the component is used on the actual page

<details>
<summary>Screenshots</summary>

image

image

</details>

## Instructions to test

- View the design: check the BackToTop story in the Storybook
- Test in action: check the index page

### Operating System

- [x] MacOS
- [ ] iOS
- [ ] iPadOS
- [ ] Windows

### Browser

- [x] Chrome
- [ ] Firefox ESR
- [x] Firefox
- [x] Safari
- [x] Edge

### CODE REVIEW

**Review by Scotchester — CHANGES_REQUESTED** [review]
This is fantastic, Albina! Great work diving into this unfamiliar repo and taking care of everything that needed to be done for this.

I have two requests for changes, though:

1. Let's not call it a "block". We would define blocks as things that actually hold an individual page's content, whereas this is more of a piece of the global web site or app's interface. I think I would just name the component "BackToTop", and maybe add it to a new "Utilities" section in Storybook? Curious for @stephiescastle's opinion on this when she has a minute.
2. Let's not use an `id` attribute in the markup or for locating the button in the JS, because I can envision a scenario where someone wants to put multiple BackToTop buttons on a page, like at the end of each item in an FAQ or something. Could you modify the JS to handle that potential scenario?

**Comment by stephiescastle** [comment]
> 1. I think I would just name the component "BackToTop", and maybe add it to a new "Utilities" section in Storybook

@Scotchester @albinazs I like this idea! Let's do it.

Thank you both.

**Comment by albinazs** [comment]
thank you @Scotchester and @stephiescastle!
PR with updated component's name and docs is ready for review

**Review by Scotchester — CHANGES_REQUESTED** [review]
Getting close, @albinazs! A couple final touches needed:

1. In the icon-only layout, we need to ensure that screen readers will read something more than just "button". I think the easiest thing would be use the `sr-only` and `sm:not-sr-only` Tailwind classes on `.label-text`.
2. I'd love it if the `data-alwaysvisible` data attribute to be all that you needed to control that feature, but currently one has to also add the `always-visible` class to the button element, as well. This could be done by modifying the SCSS to end up with a `.BackToTop[data-alwaysvisible] button` selector that does the `@apply block;`.

**Comment by albinazs** [comment]
thank you, @Scotchester, all done. 
I've also simplified `data-alwaysvisible` attribute a bit - ready for review

**Review by Scotchester — APPROVED** [review]
Great work on this, @albinazs! Merge when ready.

**Pull request merged**
