### PR TITLE
feature: GitHub gist embed block

### PR DESCRIPTION
**Pull request by jamesray**
### Checklist

- [x] Include a description of your pull request and instructions for the reviewer to verify your work.
- [x] Link to the issue if this PR is issue-specific.
- [ ] Create/update the corresponding story if this includes a UI component.
- [ ] Create/update documentation. If not included, tell us why.
- [ ] List the environments / browsers in which you tested your changes.
- [ ] Tests, linting, or other required checks are passing.
- [ ] PR has an informative and human-readable title
  - PR titles are used to generate the change log in [releases](../releases); good ones make that easier to scan.
  - PRs will be broadly categorized in the change log, but for even easier scanning, consider prefixing with a component name or other useful categorization, e.g., "BaseButton: fix layout bug", or "Storybook: Update dependencies".
- [ ] PR has been tagged with a [SemVer](https://semver.org/) label and a [general category label](https://github.com/nasa-jpl/explorer-1/blob/52994b671411f55961d7beb8851d4580ac3f434f/.github/release-drafter.config.yml#L21-L39), or skip-changelog.
  - These tags are used to do the aforementioned broad categorization in the change log and determine what the next release's version number should be.
  - [Release Drafter](https://github.com/marketplace/actions/release-drafter) will attempt to do the category labeling for you! Please double-check its work.

## Description

gist block, embed gists with just a URL and caption (links to github source)

## Instructions to test

`make vue-storybook` see [the blockGist story here](http://localhost:6006/?path=/story/components-blocks-blockgist--base-story&globals=variant:ThemeVariantDark) 

### Operating System

- [x] macOS
- [ ] iOS
- [ ] iPadOS
- [ ] Windows

### Browser

- [x] Chrome
- [x] Firefox ESR
- [x] Firefox
- [x] Safari
- [ ] Edge

### CODE REVIEW

**Comment by jamesray** [comment]
https://github.com/nasa-jpl/www/issues/173#issuecomment-2293349164

**Review by stephiescastle — CHANGES_REQUESTED** [review]
@jamesray would you be able to address the accessibility issue? You can determine the exact issue by opening storybook, going to the BlockGist story, then viewing the accessibility tab.

**Comment by stephiescastle** [comment]
Supports https://github.com/nasa-jpl/www/issues/173

**Review by stephiescastle — COMMENTED** [review]
One more note: the block also needs to be added to `BlockStreamfield`

Thank you!

**Comment by jamesray** [comment]
Changes requested are done. integrated into frontend at nasa-jpl/www [#385](https://github.com/nasa-jpl/www/pull/385)

**Review by stephiescastle — COMMENTED** [review]
@jamesray Looks good to me. I can't recreate the failing accessibility test that CI found.

Mind updating this with latest main? Then we'll let actions run again and see what happens.

**Comment by jamesray** [comment]
@stephiescastle passed, I can remerge in the other changes to main tho

**Review by stephiescastle — APPROVED** [review]

**Pull request merged**
